/* 启动条件原因编号同时用于输出快照与屏幕图标，已有编号不可重排。 */
#ifndef HT_OUTPUT_REASON_H
#define HT_OUTPUT_REASON_H
#include <stdint.h>
enum output_reason {
    OUTPUT_REASON_NONE, OUTPUT_REASON_INIT, OUTPUT_REASON_SHUTDOWN,
    OUTPUT_REASON_INPUT_IO, OUTPUT_REASON_INPUT_STALE, OUTPUT_REASON_SCREEN,
    OUTPUT_REASON_ENABLE, OUTPUT_REASON_DOOR, OUTPUT_REASON_SENSOR,
    OUTPUT_REASON_DC, OUTPUT_REASON_COIL, OUTPUT_REASON_OC, OUTPUT_REASON_OV,
    OUTPUT_REASON_SUPPLY, OUTPUT_REASON_SAMPLE_IO, OUTPUT_REASON_SAMPLE_STALE,
    OUTPUT_REASON_TEMP_STALE,
    OUTPUT_REASON_NTC1_OPEN, OUTPUT_REASON_NTC2_OPEN, OUTPUT_REASON_NTC3_OPEN,
    OUTPUT_REASON_NTC1_INVALID, OUTPUT_REASON_NTC2_INVALID, OUTPUT_REASON_NTC3_INVALID,
    OUTPUT_REASON_NTC1_HOT, OUTPUT_REASON_NTC2_HOT, OUTPUT_REASON_NTC3_HOT,
    OUTPUT_REASON_FAULT, OUTPUT_REASON_BUSY, OUTPUT_REASON_RELAYS, OUTPUT_REASON_TARGET,
    OUTPUT_REASON_COUNT
};
#define OUTPUT_REASON_BIT(reason) (UINT32_C(1) << ((reason) - 1u))
#endif
