CONFIG_MCUBOOT_SERIAL=y
CONFIG_BOOT_SERIAL_UART=y
CONFIG_BOOT_SERIAL_ENTRANCE_GPIO=n
CONFIG_BOOT_SERIAL_WAIT_FOR_DFU=y
CONFIG_BOOT_SERIAL_WAIT_FOR_DFU_TIMEOUT=3000
CONFIG_BOOT_SERIAL_NO_APPLICATION=y
CONFIG_BOOT_MGMT_ECHO=y
CONFIG_BOOT_SERIAL_IMG_GRP_HASH=y
CONFIG_BOOT_ERASE_PROGRESSIVELY=y
CONFIG_BOOT_VALIDATE_SLOT0=y
CONFIG_BOOT_GO_HOOKS=y
CONFIG_MCUBOOT_ACTION_HOOKS=y

CONFIG_GPIO=y
CONFIG_I2C=y
CONFIG_I2C_STM32_TRANSFER_TIMEOUT_MSEC=20
CONFIG_FLASH=y
CONFIG_PM=n
CONFIG_PICOLIBC=y
CONFIG_COMMON_LIBC_MALLOC_ARENA_SIZE=0
CONFIG_LOG=n
CONFIG_CONSOLE=n
CONFIG_UART_CONSOLE=n
CONFIG_PRINTK=n
CONFIG_BOOT_BANNER=n
CONFIG_MAIN_STACK_SIZE=8192
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=1024
CONFIG_ASSERT=y
